/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    /** DESIGN.md responsive ladder: ≤419, 420–640, 641–833, 834–1067, 1068–1439, 1440+. */
    screens: {
      sm: "420px",
      md: "641px",
      lg: "834px",
      xl: "1068px",
      "2xl": "1440px",
    },
    extend: {
      fontSize: {
        micro: ["10px", { lineHeight: "1.35" }],
        mini: ["11px", { lineHeight: "1.35" }],
        caption: ["12px", { lineHeight: "1.45" }],
        meta: ["13px", { lineHeight: "1.45" }],
        "body-sm": ["14px", { lineHeight: "1.55" }],
        body: ["16px", { lineHeight: "1.65" }],
        "body-lg": ["18px", { lineHeight: "1.6" }],
        "title-sm": ["20px", { lineHeight: "1.3" }],
        "title-md": ["24px", { lineHeight: "1.22" }],
        "title-lg": ["30px", { lineHeight: "1.18" }],
        "display-sm": ["34px", { lineHeight: "1.14" }],
        "display-md": ["40px", { lineHeight: "1.08" }],
        "display-lg": ["56px", { lineHeight: "1.02" }],
        "display-xl": ["72px", { lineHeight: "0.98" }],
        "display-2xl": ["88px", { lineHeight: "0.96" }],
        "display-3xl": ["104px", { lineHeight: "0.94" }],
        "metric-sm": ["24px", { lineHeight: "1" }],
        "metric-md": ["32px", { lineHeight: "1" }],
        "metric-lg": ["48px", { lineHeight: "1" }],
        "metric-xl": ["72px", { lineHeight: "0.95" }],
      },
      fontFamily: {
        sans: ["var(--font-family)"],
        mono: ["var(--font-mono-family)"],
      },
      colors: {
        bazi: {
          background: "hsl(var(--bazi-background))",
          surface: "hsl(var(--bazi-surface))",
          "surface-elevated": "hsl(var(--bazi-surface-elevated))",
          "surface-muted": "hsl(var(--bazi-surface-muted))",
          "surface-glass": "hsl(var(--bazi-surface-glass))",
          "surface-tinted": "hsl(var(--bazi-surface-tinted))",
          "surface-tinted-strong": "hsl(var(--bazi-surface-tinted-strong))",
          "surface-warm": "hsl(var(--bazi-surface-warm))",
          ink: "hsl(var(--bazi-ink))",
          "ink-secondary": "hsl(var(--bazi-ink-secondary))",
          "ink-muted": "hsl(var(--bazi-ink-muted))",
          "ink-placeholder": "hsl(var(--bazi-ink-placeholder))",
          primary: "hsl(var(--bazi-primary))",
          "primary-foreground": "hsl(var(--bazi-primary-foreground))",
          secondary: "hsl(var(--bazi-secondary))",
          tertiary: "hsl(var(--bazi-tertiary))",
          "ai-accent": "var(--bazi-ai-accent)",
          success: "hsl(var(--bazi-success))",
          "success-soft": "hsl(var(--bazi-success-soft))",
          warning: "hsl(var(--bazi-warning))",
          "warning-soft": "hsl(var(--bazi-warning-soft))",
          danger: "hsl(var(--bazi-danger))",
          "danger-soft": "hsl(var(--bazi-danger-soft))",
          "danger-hover": "var(--bazi-danger-hover)",
          info: "hsl(var(--bazi-info))",
          "info-soft": "hsl(var(--bazi-info-soft))",
          link: "hsl(var(--bazi-link))",
          "link-soft": "hsl(var(--bazi-link-soft))",
          border: "hsl(var(--bazi-border))",
          "border-soft": "hsl(var(--bazi-border-soft))",
          "border-strong": "hsl(var(--bazi-border-strong))",
          input: "hsl(var(--bazi-input))",
        },
        brand: {
          primary: "var(--bazi-brand-primary)",
          secondary: "var(--bazi-brand-secondary)",
          tertiary: "var(--bazi-brand-tertiary)",
          highlight: "var(--bazi-brand-highlight)",
        },
      },
      boxShadow: {
        "bazi-define": "var(--bazi-brand-shadow-define)",
        "bazi-lift": "var(--bazi-brand-shadow-lift)",
        bazi: "var(--bazi-brand-shadow-float)",
        "bazi-sm": "var(--bazi-shadow-sm)",
        "bazi-md": "var(--bazi-shadow-md)",
        "bazi-lg": "var(--bazi-shadow-lg)",
        "bazi-xl": "var(--bazi-shadow-xl)",
        "bazi-glow": "var(--bazi-shadow-glow)",
        control: "var(--bazi-shadow-control)",
        "control-checked": "var(--bazi-shadow-control-checked)",
      },
      backdropBlur: {
        xs: "var(--bazi-blur-xs)",
        sm: "var(--bazi-blur-sm)",
        md: "var(--bazi-blur-md)",
        lg: "var(--bazi-blur-lg)",
        xl: "var(--bazi-blur-xl)",
      },
      transitionDuration: {
        fast: "var(--bazi-motion-fast)",
        base: "var(--bazi-motion-base)",
        slow: "var(--bazi-motion-slow)",
      },
      transitionTimingFunction: {
        "smooth-out": "var(--bazi-ease-standard)",
      },
      borderRadius: {
        none: "0px",
        control: "var(--bazi-radius-control)",
        sm: "var(--bazi-radius-sm)",
        md: "var(--bazi-radius-md)",
        lg: "var(--bazi-radius-lg)",
        xl: "var(--bazi-radius-xl)",
        "2xl": "var(--bazi-radius-2xl)",
        "3xl": "var(--bazi-radius-3xl)",
        tail: "var(--bazi-radius-tail)",
        full: "var(--bazi-radius-pill)",
      },
      zIndex: {
        background: "var(--bazi-z-background)",
        base: "var(--bazi-z-base)",
        raised: "var(--bazi-z-raised)",
        focus: "var(--bazi-z-focus)",
        sticky: "var(--bazi-z-sticky)",
        floating: "var(--bazi-z-floating)",
        overlay: "var(--bazi-z-overlay)",
        popup: "var(--bazi-z-popup)",
        toast: "var(--bazi-z-toast)",
        debug: "var(--bazi-z-debug)",
      },
      minHeight: {
        touch: "var(--bazi-touch)",
      },
    },
  },
  plugins: [],
};
